version: "3.8"
services:

  db:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1qaz
      POSTGRES_USER: test
      POSTGRES_DB: yurez
    ports:
      - "5432:5432"
    expose:
      - "5432"

  # Django
  web:
    build:
      context: .
    hostname: web
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    expose:
      - "8001"
    restart: always
    links:
      - "db:postgres"
    depends_on:
      - "db"
